config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :record_labels
  resources :master_releases
  resources :releases
  resources :tracks
  resources :formats
  resources :images
end

app/models/artist.rb
class Artist < ApplicationRecord
  alias_attribute :id, :artist_id
  self.table_name = "artist"
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
    
    @entities = @artists;
    @attributes = [
      {sym: :name, hr_name: "Name", is_link_attribute: true}
    ]
  end
  
  def edit
    @artist = Artist.find(params[:id])
  end
  
  def update
    @artist = Artist.find(params[:id])
      
    if @artist.update_attributes artist_params
      redirect_to action: "index"
    else
      # TODO
    end
  end
  
  def show
    @artist = Artist.find(params[:id])
    @master_releases = MasterRelease.where(artist_id: params[:id])
      
    @attributes = [
      {sym: :title, hr_name: "Title", is_link_attribute: true}
    ]
    
    @entities = @master_releases
      
    session[:artist_id] = @artist.id
  end
  
  def new
    @artist = Artist.new
  end
  
  def destroy
    @artist = Artist.find(params[:id])
    @artist.delete

    redirect_to action: "index"
  end
  
  def create
    @artist = Artist.new artist_params
    
    if @artist.save
      redirect_to action: "index"
    else
      # TODO
    end
  end
  
  private
  
  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= form_for @artist do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.submit "Save Changes" %>
<% end %>

app/views/artists/index.html.erb
<h1>Artists</h1>

<%= render 'layouts/item_table' %>
  
<a href="<%= new_artist_path %>">Create New Artist</a>

app/views/artists/new.html.erb
<h1>Create New Artist</h1>

<%= form_for @artist do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.submit "Create Artist" %>
<% end %>

app/views/artists/show.html.erb
<%
  provide :breadcrumbs, (
    '' + link_to("Artists", artists_path)
  ).html_safe
%>

<h1><%= @artist.name %></h1>

<h2>Master Releases</h2>
  
<%= render 'layouts/item_table' %>

<%= link_to 'Create New Master Release', new_master_release_path(artist_id: @artist.id) %>
  